### ISSUE TITLE
Using "SELECT ... FROM TOPIC_A WITHSTUCTURE" for array of structures

### ISSUE THREAD

**Issue by nirvanesque** [Landoop/kafka-connect-kcql-smt#1]
Hello,

We are following your developments for Kafka Connectors as we are exploring the usability of sinks with different DB [Cassandra, InfluxDB, Druid, ...], "without" using Spark Streaming. (a colleague of mine was exchanging with you on your Druid development)

Our Kafka messages use the Avro schema (which is recommended for nested structures), and often we have array of structures as follows:
```
"fields" : [
	      {"name": "metrics", "type": "long"},
	      {"name": "values", "type": "string"}
	      ]
```

We would like to know if and how we can handle this using the construct "SELECT ... FROM TOPIC_A WITHSTUCTURE" ? 
Do we then need to pass it into another extra topic to extract separately each metric (key-value pairs) in the array ?

Thanks in advance for all your advice.

**Comment by stheppi** [comment]
@nirvanesque 
we are planning to bring the functionality in the connectors themselves.

what you showed me as schema is not an Avro Array but part of an Avro Record.

so depends on what you want to select. if you don't do transformations just use the raw connectors with KCQL `SELECT * FROM metricsTopic`.

If you want to use the select with nested fields while still retaining the way the incoming message structure is you can do this:

`SELECT ingredients.*,ingredients.name as fieldName, ingredients.sugar as fieldSugar FROM topic withstructure`

In the above you basically retain the array of ingredients but you are renaming the name/sugar fields.
