### ISSUE TITLE
Is there any documentation on how to install it?

### ISSUE THREAD

**Issue by kccheung** [Landoop/kafka-connect-kcql-smt#3]
As title, would like to install but no clues how to start.

**Comment by cricket007** [comment]
It's a Kafka Connect Transform, so if you build the JAR, and place it on the connect CLASSPATH, (or plugin.path with Confluent 4.0), it should be available

**Comment by kccheung** [comment]
I am using the connector "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector" and would like to exclude certain fields to be sinked to a topic. Is this plugin allows to do a this filtering. If so, and provided I installed it in my classpath, is the curl command looks like something below?

`
curl -X "POST" "http://<my_ip>:28083/connectors/" \
     -H "Content-Type: application/json" \
     -d $'{
  "name": "es_sink_abc",
  "config": {
    "topics": "abc",
    "tasks.max": 2,
    "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "key.ignore": "true",
    "schema.ignore": "true",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "value.converter.schemas.enable": false,
    "type.name": "kafka-connect",
    "topic.index.map": "'abc:abc",
    "connection.url": "http://elasticsearch:9200",
    "connect.transforms.sql.value": "SELECT a, b as fieldSugar FROM abc"
  }
`

**Comment by stheppi** [comment]
That's how you would use it.

you can always check our connector for ES  https://lenses.stream/connectors/sink/elastic5.html 
it has that capability you want as part of the configuration and you don't need the SMT.

I am going to close the issues, since it is not an issue and @cricket007 has responded to how you would use this.
